disabled_rules:
- cyclomatic_complexity
- force_cast
- function_body_length
- inclusive_language
- line_length
- type_body_length
- todo
- weak_delegate
- xctfail_message
- file_length
- function_parameter_count
- large_tuple
- type_name
# На время, пока нет тестов
- empty_xctest_method
- overridden_super_call

opt_in_rules:
- anyobject_protocol
- array_init
- balanced_xctest_lifecycle
- capture_variable
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- convenience_type
- discarded_notification_center_observer
- discouraged_assert
- discouraged_object_literal
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- expiring_todo
- explicit_init
- fallthrough
- fatal_error_message
#- file_name
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- identical_operands
- implicit_return
- joined_default_parameter
- last_where
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_literal_brackets
- multiline_parameters
- nimble_operator
- nslocalizedstring_key
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- private_action
- private_outlet
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- raw_value_for_camel_cased_codable_enum
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- required_enum_case
- sorted_first_last
- static_operator
- strict_fileprivate
- switch_case_on_newline
- test_case_accessibility
- toggle_bool
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- unused_declaration
- unused_import
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition

excluded:
  - Pods/

reporter: "xcode"

identifier_name:
    min_length: 1
    max_length: 60
    allowed_symbols: "_"

#file_name:
#    suffix_pattern: "Extensions?|\\+.*"

nesting:
    type_level: 3

warning_threshold: 1500

